export const FETCH_USERS_ACTION = "FETCH_USERS_ACTION";
export const FETCH_USERS_ACTION_SUCCESS = "FETCH_USERS_ACTION_SUCCESS";
export const FETCH_USERS_ACTION_ERROR = "FETCH_USERS_ACTION_ERROR";
export const CANCELLING_USERS_ACTION = "CANCELLING_USERS_ACTION";

export const CONFIRM_CANCEL_USER_ACTION = "CONFIRM_CANCEL_USER_ACTION";
export const CONFIRM_CANCEL_USER_ACTION_SUCCESS =
  "CONFIRM_CANCEL_USER_ACTION_SUCCESS";
export const CONFIRM_CANCEL_USER_ACTION_ERROR =
  "CONFIRM_CANCEL_USER_ACTION_ERROR";
export const HIDE_TOAST_ACTION = "HIDE_TOAST_ACTION";
