export const INCREMENT_ACTION = "INCREMENT_ACTION";
export const DECREMENT_ACTION = "DECREMENT_ACTION";
export const RESET_ACTION = "RESET_ACTION";
export const HIDE_TOAST_ACTION = "HIDE_TOAST_ACTION"